### ISSUE TITLE
你好有个问题想问一下

### ISSUE THREAD

**Issue by yrmatou** [cumt-robin/express-blog-backend#1]
您遇到过stream只回流部分吗？比如写个诗，它只返回首句下面的就不返回了

**Comment by cumt-robin** [comment]
可以调整一下 max_tokens 参数

**Comment by yrmatou** [comment]
> 可以调整一下 max_tokens 参数

好的，谢谢。有个小问题，他们这个免费配额是多少？就是可以请求多少次？

**Comment by cumt-robin** [comment]
应该是 18 美元，根据 token 计费的，在文章中有提到，https://juejin.cn/post/7176539666210881592#heading-2，具体可以上他们网站看看。

**Comment by yrmatou** [comment]
> 应该是 18 美元，根据 token 计费的，在文章中有提到，[https://juejin.cn/post/7176539666210881592#heading-2，具体可以上他们网站看看。](https://juejin.cn/post/7176539666210881592#heading-2%EF%BC%8C%E5%85%B7%E4%BD%93%E5%8F%AF%E4%BB%A5%E4%B8%8A%E4%BB%96%E4%BB%AC%E7%BD%91%E7%AB%99%E7%9C%8B%E7%9C%8B%E3%80%82)

好的 谢谢
