### ISSUE TITLE
登陆以后报“对不起，您还未获得授权”

### ISSUE THREAD

**Issue by renwofei423** [cumt-robin/express-blog-backend#2]
正确输入密码以后，报“对不起，您还未获得授权”

文章是有内容的，至少证明数据库查询没问题，请问还需要设置什么导致没授权？

**Comment by renwofei423** [comment]
http://oneele.com

账号密码是默认的

**Comment by cumt-robin** [comment]
建议后续问题都加微信聊，github看不及时
